services:
  postgres:
    image: postgres:16
    container_name: nohvex-exchange-pg
    restart: unless-stopped
    ports:
      - "5434:5432"
    env_file:
      - .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

